"""add job retry fields

Revision ID: 8bc3ee1e2805
Revises: de8caf07780d
Create Date: 2026-10-07 21:41:51.096979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc3ee1e2805'
down_revision: Union[str, Sequence[str], None] = 'de8caf07780d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('attempts', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('jobs', sa.Column('max_attempts', sa.Integer(), nullable=False, server_default="3"))
    op.add_column('jobs', sa.Column('last_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'last_error')
    op.drop_column('jobs', 'max_attempts')
    op.drop_column('jobs', 'attempts')
    # ### end Alembic commands ###
